[package]
name = "async-mutex"
version = "0.1.2"
authors = ["real <real@freedomlayer.org>", "Kamyuen Tse <kevin.xjy@gmail.com>", "Do Duy <juchiast@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.9" }

[dev-dependencies]
