[package]
name = "async_mutex"
version = "0.1.1"
authors = ["real <real@freedomlayer.org>", "Kamyuen Tse <kevin.xjy@gmail.com>", "Do Duy <juchiast@gmail.com>"]

[dependencies]
futures = "0.1"
log = "0.4"

[dev-dependencies]
tokio-core = "0.1.17"
tokio = "0.1.7"
